set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_CROSSCOMPILING TRUE)

set(MINGW_ARCH ${ARCH}-w64-mingw32)
set(TARGET ${ARCH}-w64-mingw32-gcc)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(CUSTOM_BUILD_PARAMS "${CUSTOM_BUILD_PARAMS} -DWIN32")
SET(CUSTOM_BUILD_PARAMS "${CUSTOM_BUILD_PARAMS} -D_UNICODE")
SET(CUSTOM_BUILD_PARAMS "${CUSTOM_BUILD_PARAMS} -DUNICODE")
SET(CUSTOM_BUILD_PARAMS "${CUSTOM_BUILD_PARAMS} -D__GNUC__=4") # -mwindows

set (CMAKE_EXECUTABLE_SUFFIX ".exe")

set(CMAKE_POSITION_INDEPENDENT_CODE OFF)

# SET(LINK_LIBRARIES stdc++) #msvcrt