set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_CROSSCOMPILING TRUE)

set(TARGET ${ARCH}-w64-mingw32-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(CUSTOM_BUILD_PARAMS "${CUSTOM_BUILD_PARAMS} -DWIN32 -D_UNICODE -DUNICODE -D__GNUC__=4")
SET(CUSTOM_BUILD_PARAMS "${CUSTOM_BUILD_PARAMS} -fms-extensions -frtti -fno-exceptions")
SET(CUSTOM_LINKER_PARAMS "${CUSTOM_LINKER_PARAMS} -Wl,--enable-auto-import")
SET(CUSTOM_LINKER_PARAMS "${CUSTOM_LINKER_PARAMS} -Wl,--enable-auto-image-base")
SET(CUSTOM_LINKER_PARAMS "${CUSTOM_LINKER_PARAMS} -Wl,--add-stdcall-alias")
SET(CUSTOM_LINKER_PARAMS "${CUSTOM_LINKER_PARAMS} -static")

set (CMAKE_EXECUTABLE_SUFFIX ".exe")

set(CMAKE_POSITION_INDEPENDENT_CODE OFF)

SET(LINK_LIBRARIES stdc++) #msvcrt